export const LOGIN_USER = 'LOGIN_USER';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

export const ADDING_WISHLIST = 'ADDING_WISHLIST';
export const ADDING_WISHLIST_FAIL = 'ADDING_WISHLIST_FAIL';
export const ADDING_WISHLIST_SUCCESS = 'ADDING_WISHLIST_SUCCESS';
export const DELETING_WISHLIST = 'DELETING_WISHLIST';
export const DELETING_WISHLIST_FAIL = 'DELETING_WISHLIST_FAIL';

export const FILTER_SUBCATEGORY = 'FILTER_SUBCATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';

export const ADDING_CUSTOMIZE_TO_CART = 'ADDING_CUSTOMIZE_TO_CART';
export const ADDING_CUSTOMIZE_TO_CART_SUCCCESS = 'ADDING_CUSTOMIZE_TO_CART_SUCCCESS';
export const ADDING_CUSTOMIZE_TO_CART_FAIL = 'ADDING_CUSTOMIZE_TO_CART_FAIL';
export const LOAD_STYLES_CATALOGUES = 'LOAD_STYLES_CATALOGUES';
export const LOAD_STYLES_CATALOGUES_SUCCESS = 'LOAD_STYLES_CATALOGUES_SUCCESS'
export const LOAD_STYLES_CATALOGUES_FAIL = 'LOAD_STYLES_CATALOGUES_FAIL'
export const UPDATE_STcYLES_VALUES = 'UPDATE_STYLES_VALUES';
export const SET_BESPOKE_VALUES = 'SET_BESPOKE_VALUES'; 

export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS'
export const ADD_REQUEST_FAIL = 'ADD_REQUEST_FAIL'

export const SET_USER_VALUES = 'SET_USER_VALUES';
export const ADD_CART_ITEM = 'ADD_CART';
export const GET_CART_ITEM = 'GET_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const LOAD_BESPOKE_PRODUCT = 'LOAD_BESPOKE_PRODUCT';
export const LOAD_BESPOKE_PRODUCT_SUCCESS = 'LOAD_BESPOKE_PRODUCT_SUCCESS';
export const LOAD_BESPOKE_PRODUCT_FAILURE = 'LOAD_BESPOKE_PRODUCT_FAILURE';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SET_PRODUCT_VALUES = 'SET_PRODUCT_VALUES';
export const CART_COUNT = 'CART_COUNT';
export const EMPTY_CART = 'EMPTY_COUNT';
export const SET_CUSTOMIZE_VALUES = 'SET_CUSTOMIZE_VALUES';

export const MEASUREMENT_VALUES = 'MEASUREMENT_VALUES';
export const SAVE_MEASUREMENT_SUCCESS = 'SAVE_MEASUREMENT_SUCCESS';
export const SAVE_MEASUREMENT_FAIL = 'SAVE_MEASUREMENT_FAIL';
export const ADDING_MEASUREMENT = 'ADDING_MEASUREMENT';
export const GET_MEASUREMENT = 'GET_MEASUREMENT';
export const REMOVE_MEASUREMENT = 'REMOVE_MEASUREMENT';

export const GET_USER_ADDRESS = 'GET_USER_ADDRESS';

export const LOAD_NEW_ARRIVALS = 'LOAD_NEW_ARRIVALS';
export const LOAD_NEW_ARRIVALS_SUCCESS = 'LOAD_NEW_ARRIVALS_SUCCESS';
export const LOAD_NEW_ARRIVALS_FAIL = 'LOAD_NEW_ARRIVALS_FAIL';
export const UPDATE_PRODUCT_VALUES = 'UPDATE_PRODUCT_VALUES';
export const RESET_PRODUCT_LIST = 'RESET_PRODUCT_LIST';

export const FREQUENTLY_BOUGHT_SUCCESS = 'FREQUENTLY_BOUGHT_SUCCESS';
export const FREQUENTLY_BOUGHT_FAIL = 'FREQUENTLY_BOUGHT_FAIL';

export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL';
export const LOAD_MORE_PRODUCT = 'LOAD_MORE_PRODUCT';

export const PROFILE_TAB = 'PROFILE_TAB';

export const ORDER = 'ORDER';

export const PROFILE_MEASUREMENT = 'PROFILE_MEASUREMENT';
export const SAVE_LAST_URL = 'SAVE_LAST_URL';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const RESETTING_PASSWORD = 'RESETTING_PASSWORD';
export const RESET_FAILED = 'RESET_FAILED';
export const RESET_SUCCESS = 'RESET_SUCCESS';

export const ADDING_ADDRESS = 'ADDING_ADDRESS';
export const ADDING_ADDRESS_FAIL = 'ADDING_ADDRESS_FAIL';
export const DELETING_ADDRESS = 'DELETING_ADDRESS';
export const DELETING_ADDRESS_FAIL = 'DELETING_ADDRESS_FAIL';

export const REGISTERING_USER = 'REGISTERING_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_USER_PROFILE_FAIL = 'EDIT_USER_PROFILE_FAIL';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const GUEST_CHECKOUT = 'GUEST_CHECKOUT';
export const USER_CHECKOUT = 'USER_CHECKOUT';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const SET_DETAILS_DEFAULT = 'SET_DETAILS_DEFAULT';
export const SET_DETAILS_VALUES = 'SET_DETAILS_VALUES';
export const PRODUCT_COLOR_CHANGE = 'PRODUCT_COLOR_CHANGE';

export const CLEAR_CART = 'CLEAR_CART';
export const SHIPPING_FEE = 'SHIPPING_FEE';
export const GET_USER_SHIPPING_PRICE = 'GET_USER_SHIPPING_PRICE';

export const SEARCHING_PRODUCT = 'SEARCHING_PRODUCT';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_FAILED = 'SEARCHING_FAILED';
export const RESET_SEARCH_LIST = 'RESET_SEARCH_LIST';

export const SET_DRAWER_VALUES = 'SET_DRAWER_VALUES';
export const PRODUCT_TYPE_CHANGED= 'PRODUCT_TYPE_CHANGED';
export const RESET_DRAWER_VALUES = 'RESET_DRAWER_VALUES';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const LOGO_FETCH_SUCCESS = 'LOGO_FETCH_SUCCESS';
export const LOGO_FETCH_FAIL = 'LOGO_FETCH_FAIL';

export const LOADING_DESIGNER_PRODUCT = 'LOADING_DESIGNER_PRODUCT';
export const DESIGNER_PRODUCT_SUCCESS = 'DESIGNER_PRODUCT_SUCCESS';
export const DESIGNER_PRODUCT_FAIL = 'DESIGNER_PRODUCT_FAIL';

export const LOADING_SUB_CATEGORY_PRODUCTS = 'LOADING_SUB_CATEGORY_PRODUCTS';
export const SUB_CATEGORY_PRODUCTS_SUCCESS = 'SUB_CATEGORY_PRODUCTS_SUCCESS';
export const SUB_CATEGORY_PRODUCTS_FAIL = 'SUB_CATEGORY_PRODUCTS_FAIL';
export const SET_SUB_CATEGORY_VALUES = 'SET_SUB_CATEGORY_VALUES';
export const RESET_SUBCATEGORY_VALUES = 'RESET_SUBCATEGORY_VALUES';
export const LOAD_MORE_SUB = 'LOAD_MORE_SUB';


export const USER_SINGLE_ADDRESS = 'USER_SINGLE_ADDRESS';
export const USER_PREFERENCE = 'USER_PREFERENCE';
export const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';
export const TRACK_USER_ORDER = 'TRACK_USER_ORDER';
export const BESPOKE_BIDS = 'BESPOKE_BIDS';
export const VIEW_BESPOKE_BID = 'VIEW_BESPOKE_BID';

export const SAVE_TRANSFER_INFO = 'SAVE_TRANSFER_INFO';



